### ISSUE TITLE
Ugly ending of script 

### ISSUE THREAD

**Issue by markboenigk** [fdesena/notebooks#1]
I would just use a return statement ( or no return statement since you don't return anything) in the case_solved() function.
`An exception has occurred, use %tb to see the full traceback.

SystemExit: The End.
/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3560: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)`

**Comment by fdesena** [comment]
Great idea. I will change the exit0 function by return, so I just get an output in the end. Thank @markboenigk
