### ISSUE TITLE
Low readability of list 

### ISSUE THREAD

**Issue by markboenigk** [fdesena/notebooks#2]
I think you can try to improve the readability of the output of the list by looping through it or creating a table 
https://github.com/fdesena/notebooks/blob/30629f10e098c0838b945fdc470acd2705b935c8/sherlock_holmes_mistery_final.ipynb?short_path=b6888ed#L236

**Comment by fdesena** [comment]
Hey Mark, now I printed it as an enumerated list. So it is way better to read. I added  this to the code:

for i, name in enumerate(names):
        print(f"{i+1}. {name}")
    return names

Thanks for the feedback.
